"""add page tracking and conversation metadata

Revision ID: 0c4f9ee600ce
Revises: dd9e73e2f241
Create Date: 2026-07-24 10:44:35.342654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4f9ee600ce'
down_revision: Union[str, Sequence[str], None] = 'dd9e73e2f241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_pages_document_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('title', sa.String(), nullable=True))
    # server_default backfills existing rows (real chat sessions already
    # exist); the ORM model also sets these defaults for future inserts.
    op.add_column('chat_sessions', sa.Column('pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chat_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # server_default backfills existing chunk rows (predates page tracking)
    # as page 1, since that's the only page they can be attributed to.
    op.add_column('chunks', sa.Column('page_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'page_count')
    op.drop_column('chunks', 'page_number')
    op.drop_column('chat_sessions', 'updated_at')
    op.drop_column('chat_sessions', 'pinned')
    op.drop_column('chat_sessions', 'title')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    # ### end Alembic commands ###
