"""add usage_counters table

Revision ID: 52b2c7c0090b
Revises: e09f7ec8b723
Create Date: 2026-07-24 17:39:15.524224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b2c7c0090b'
down_revision: Union[str, Sequence[str], None] = 'e09f7ec8b723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_counters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('documents_uploaded', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_usage_counters_user_date')
    )
    op.create_index(op.f('ix_usage_counters_usage_date'), 'usage_counters', ['usage_date'], unique=False)
    op.create_index(op.f('ix_usage_counters_user_id'), 'usage_counters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_counters_user_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_usage_date'), table_name='usage_counters')
    op.drop_table('usage_counters')
    # ### end Alembic commands ###
