"""add global_usage_counters table

Revision ID: 7cf75bdda2f8
Revises: 52b2c7c0090b
Create Date: 2026-07-25 14:11:50.233788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf75bdda2f8'
down_revision: Union[str, Sequence[str], None] = '52b2c7c0090b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_usage_counters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('total_documents_uploaded', sa.Integer(), nullable=False),
    sa.Column('total_questions_asked', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_usage_counters_usage_date'), 'global_usage_counters', ['usage_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_usage_counters_usage_date'), table_name='global_usage_counters')
    op.drop_table('global_usage_counters')
    # ### end Alembic commands ###
