"""make chunk vector_id nullable

Revision ID: dd9e73e2f241
Revises: 6c23914fa305
Create Date: 2026-07-19 19:36:26.608861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9e73e2f241'
down_revision: Union[str, Sequence[str], None] = '6c23914fa305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'vector_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'vector_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
