"""add auth fields to users

Revision ID: e09f7ec8b723
Revises: 0c4f9ee600ce
Create Date: 2026-07-24 12:16:45.353091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09f7ec8b723'
down_revision: Union[str, Sequence[str], None] = '0c4f9ee600ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # hashed_password starts nullable so existing rows (the single seeded
    # MVP user) don't violate NOT NULL before being backfilled below.
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###

    # Backfill: the pre-auth MVP had one hardcoded default user
    # (default-user@ai-document-assistant.local) that owns all existing
    # documents/chat history. Give it a real, known dev password
    # ("changeme123") rather than locking that data behind an account
    # nobody can log into. Any other pre-existing row (shouldn't exist in
    # this single-user MVP, but handled defensively) gets a random,
    # unusable hash instead of guessing a password for it.
    op.execute(
        "UPDATE users SET hashed_password = "
        "'$2b$12$2ngmnorJVOQ04tnIpAc2Nu5wCs4YC6ZFdeVCJSrJJaOYIzaqcBxIa' "
        "WHERE email = 'default-user@ai-document-assistant.local' AND hashed_password IS NULL"
    )
    op.execute(
        "UPDATE users SET hashed_password = "
        "'$2b$12$o2iBPcgwFw8VRm/oLEmY7urbo2jgeFXOZ/ECRGV55h0gUVpJa4JRe' "
        "WHERE hashed_password IS NULL"
    )
    op.alter_column('users', 'hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
